import random

meme_phrases = [
    "Ше й в'єбав",
    "Сцеплєр йобаний",
    "Don't push the horses",
    "Астанавітєсь!",
    "Це ж було вже!",
    "Ці руки нічого не крали!",
    "Та за шо?!",
    "Пішов нахуй, я директор",
    "У тебя скучное лицо, тебе никто денег не даст",
    "Твій код блять як штани за 40 гривень",
    "Сука, руль вирвало",
    "Батько, тобі нормально?",
    "Якого хуя, блять, відбувається?",
    "Хуярить, як дурний",
    "Ситуація в Україні бл*дська",
    "Маємо те, що маємо",
    "Батя, я стараюсь",
    "Дедлайн був ще вчора, але ми не здаємося",
    "Моя улюблена пора року — п'ятниця вечір",
    "Ну, мені нравиться, як воно горить, як люди суєтятся, пожарки приїжджають.",
    "Олександре, скажіть, будь ласка, як вас звати?",
    "Щоб вода перетворилася на гарячу — її треба підігріти",
    "Не говорити про погане. Краще – зробити",
    "Що поганого, що я підтримую цих страусів?",
    "В гробу сміятись непристойно",
    "Коли добродій хоче срати, він танцювать не годен вальс.",
    "Все як звичайно, але більше не варто робити",
    "Якщо на одній нозі, то не бігати",
    "Якби вони були розумні, то не виходили б зі своїх компаній",
    "Не хочу нічого касатися, я вже на голові",
    "Це як щось вийшло не так",
    "Це як сімейний бізнес, а не бізнес",
    "Тобі пизда, тікай з городу",
    "А нахуя, а головне — навіщо?",
    "Єбать ти лох, звичайно",
    "Чисто на похуях",
    "Він єбанутий, єй-богу",
    "Всьо, пізда рулю",
    "Ну і хулі ти мені зробиш?",
    "Завали єбало, шеф працює",
    "Якого милого, блять?",
    "Тупо найкращий, єбать його в рот",
    "Шо ти лисий, плачеш?",
    "Це просто якийсь сюр, нахуй",
    "Nihuyasobi na oborot.",
    "Ти кому дзвониш, синок?",
    "Єбать, я роз'їбався",
    "Шо ти мелеш, сука?",
    "А я зараз вам покажу, звідки на Білорусь...",
    "Ну це вже повний пиздець, панове",
    "Він хуйні не скаже",
    "Якого прутня тут коїться?",
    "Всьо хуйня, давай по новій",
    "Ти шо, єбанувся туди лізти?",
    "Проєбали спалах",
    "Тягни кота за яйця, хулі ти чекаєш",
    "Нам пизда, але є нюанс",
    "Я єбав таку роботу",
    "Шо ти, блєдіна, накурився?",
    "Чисто під пивко потягне",
    "Тупо в гівно",
    "Сука, аж трисе",
    "Хулі ти вилупився?",
    "До пизди карі очі",
    "Та йди ти нахуй зі своїми порадами",

    # --- Політики ---
    "Сьогодні — це вже завтра, яке було вчора",
    "Краще, ніж було, вже не буде",
    "Не всі спортсмени, які спортсмени — вони спортсмени",
    "Я не хочу сказати, що це буде через рік чи два. Але через рік чи два це буде",
    "Щось сталося... ялинка впала",
    "Максимум два-три тижні",
    "Я тут. Ми всі тут",
    "Мені потрібні набої, а не підвезення",
    "Роби, як я",
    "Живемо по-новому",
    "Ми зробимо все можливе і неможливе",
    "Я вам не Кучма, я вам Кучма",
    "Скажіть, а хто це все погоджував?",

    # --- Програмісти ---
    "Talk is cheap. Show me the code.",
    "Premature optimization is the root of all evil",
    "Testing shows the presence, not the absence of bugs",
    "Debugging is twice as hard as writing the code in the first place",
    "Bad programmers worry about the code. Good programmers worry about data structures.",
    "C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do, it blows your whole leg off",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "Now you have two problems",
    "Adding manpower to a late software project makes it later",
    "My billion-dollar mistake: the null reference",
    "It's just a hobby, won't be big and professional like GNU",
    "NVIDIA, f*ck you!",
    "Focus is deciding what you're NOT going to do",
    "There are only two hard things: cache invalidation and naming things",
    "Weeks of coding can save you hours of planning",
    "It works on my machine — тоді деплоїмо машину",
    "Deleted code is debugged code",
    "Real programmers don't comment their code. If it was hard to write, it should be hard to read.",
    "Perfection is achieved when there is nothing left to take away",
    "Rewrite from scratch — найдорожча фраза в IT",

    # --- Спортсмени ---
    "Everyone has a plan until they get punched in the mouth",
    "Спокійно, дядько, спокійно",
    "Я не боксер, я актор",
    "I've missed more than 9000 shots in my career. That's why I succeed.",
    "Zlatan doesn't do auditions",
    "I am a special one",
    "Коли ти впав — це ще не поразка. Поразка — коли не встав",
    "Тренування — це коли вже не можеш, а ти ще раз",
    "Тримай дистанцію, синку",
    "Другий раунд ще не почався, а ти вже дихаєш ротом",

    # --- Громадські діячі / шоубіз ---
    "Донатьте, бляха, воно само себе не купить",
    "Обійми мене, все буде добре",
    "Слава Ісусу Христу!",
    "Хто, як не ми?",
    "Ми не здаємо своїх",
    "One more thing...",
    "It just works",
    "Stay hungry, stay foolish",
    "Дякую, що ви є. Але код перепиши",
    "Все, що нас не вбиває, іде в продакшн",
]


def snark() -> str:
    """One random meme phrase, for flavouring the MR summary."""
    return random.choice(meme_phrases)
